<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '72af8560ce28ddb51e42dc061ba35b6f',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/cswd?serverVersion=8&charset=utf8mb4',
  'ASSETS_VERSION' => '1.0.0',
  'GLOBAL_URL' => 'http://dev.cswd.com',
  'WKHTMLTOPDF_PATH' => '/usr/local/bin/wkhtmltopdf',
  'WKHTMLTOIMAGE_PATH' => '/usr/local/bin/wkhtmltoimage',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
